Feat/trainer
deep-diver/segformer-in-ml-pipeline pull request #8
Opened 2022-08-31 08:02 UTC by deep-diver

This is a draft PR, and there is an issue that I am working on:
- in the line 82(`upsampled_logits = tf.image.resize(...`), I get an error `AttributeError: Tensor object has no attribute 'size'.`

Important Note:
- I am experimenting TFX pipeline locally before Vertex AI, so small batch of data is included under `/data` directory.

To reproduce:
- Checkout `feat/trainer` branch
- Install required dependencies with `training_pipeline/requirements.txt`
- Run the following three commands in order
  - `tfx pipeline create --pipeline-path=local_runner.py --engine=local`
  - `tfx pipeline compile --pipeline-path=local_runner.py --engine=local`
  - `tfx run create --pipeline-name=segformer-training-pipeline --engine=local`

if you think I should write a notebook rather than scripts, please let me know.

2022-08-31 08:26 UTC, sayakpaul requested changes

2022-08-31 08:26 UTC, sayakpaul commented on training_pipeline/models/model.py
> +            ],  # We reverse the shape of `image` because `image.size` returns width and height.
TensorFlow tensors don't have any `size` attribute. Use `tf.shape()` or `.shape`.

2022-09-03 17:32 UTC, deep-diver commented
`preprocess` part will be updated when the adjusted TFRecords for UNET is ready.

2022-09-03 20:11 UTC, sayakpaul commented
@deep-diver is this PR ready to review?

2022-09-04 01:01 UTC, deep-diver commented
@sayakpaul 

will let you know after reflecting the changes in TFRecord

2022-09-04 13:20 UTC, deep-diver commented
@sayakpaul 

ready for review

2022-09-04 13:24 UTC, sayakpaul commented
Thanks. 

Will review tomorrow.

2022-09-05 03:53 UTC, closed without merging